# Generated by Django 3.1.6 on 2021-02-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oliverapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
